### ISSUE TITLE
does not tell me if i look just like buddy holly

### ISSUE THREAD

**Issue by IanRises** [tacohitbox/familyguyfan.club#1]
this is a very important feature that is missing from this website. ANY good website tells you if you look just like buddy holly and i feel this site can be not just good, but great, if it featured a buddy holly metric. please i am begging you
![Pokemon Tetris](https://user-images.githubusercontent.com/15117113/219275676-3d5b0834-3654-4097-b0ee-ed8bc5e8cc6b.jpg)

**Comment by tacohitbox** [comment]
fuck you

**Comment by IanRises** [comment]
ooh wee ooh i look just like buddy holly
